extraction:
  cpp:
    configure:
      - mkdir _lgtm_build_dir
      - cd _lgtm_build_dir
      - cmake -DBUILD_GTEST=OFF -DINSTAL_GTEST=OFF ..

    index:
      build_command:
        - cd _lgtm_build_dir
        - make

path_classifiers:
  library:
    - Libraries